name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-20.04, windows-2019, macos-13, macos-14]
    env:
      # Seems to have trouble parsing our setup.py, thus:
      CIBW_PROJECT_REQUIRES_PYTHON: ">=3.8"
      # Install numpy with a wheel (do NOT compile it):
      CIBW_BEFORE_BUILD: "pip install --only-binary :all: -r requirements.txt"
      # There are/were no numpy wheels for these:
      CIBW_SKIP: pp37-* pp38-* pp39-* pp310-* cp39-manylinux_i686 cp310-manylinux_i686 cp311-manylinux_i686 cp312-manylinux_i686 *-musllinux_*
      # Quick test with C code using NumPy C API:
      CIBW_TEST_COMMAND: "python {package}/Tests/test_Cluster.py"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Optional
          submodules: true  # Optional, use if you have submodules

      - name: Checkout tag/commit
        run: |
          git submodule update --init biopython
          cd biopython
          # Use commit hash if tag is still pending:
          # This should be the commit for Biopython 1.82:
          git checkout biopython-183
          cd ..


      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        with:
          package-dir: biopython
          output-dir: wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
